services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    restart: always

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip_all", "--nounixsocket"]
volumes:
  mongo-data: